### ISSUE TITLE
overwrite etc/ssl/openssl.cnf error, when use alpine v3.7

### ISSUE THREAD

**Issue by gotoworld** [yangpeng14/kube-dingtalk#1]
fetch http://mirrors.aliyun.com/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
v3.7.3-170-g2e95874e52 [http://mirrors.aliyun.com/alpine/v3.7/main/]
OK: 5720 distinct packages available
(1/33) Downgrading musl (1.1.20-r4 -> 1.1.18-r4)
(2/33) Installing libressl2.6-libcrypto (2.6.5-r0)
ERROR: libressl2.6-libcrypto-2.6.5-r0: trying to overwrite etc/ssl/cert.pem owned by ca-certificates-cacert-20190108-r0.
ERROR: libressl2.6-libcrypto-2.6.5-r0: trying to overwrite etc/ssl/openssl.cnf owned by libcrypto1.1-1.1.1b-r1.
(3/33) Installing ca-certificates (20190108-r0)
(4/33) Downgrading libstdc++ (8.3.0-r0 -> 6.4.0-r5)
(5/33) Installing binutils-libs (2.30-r2)
(6/33) Installing binutils (2.30-r2)

**Comment by yangpeng14** [comment]
Thanks
