### ISSUE TITLE
npm ERR! Error: EACCES: permission denied, access '/app'

### ISSUE THREAD

**Issue by gotoworld** [yangpeng14/kube-dingtalk#3]
`
Step 8/10 : RUN npm config set registry https://registry.npm.taobao.org && npm install --production
 ---> Running in aa8a7d9d1786
npm WARN checkPermissions Missing write access to /app
npm WARN kube-slack@3.6.0 No description
npm WARN kube-slack@3.6.0 No repository field.
npm WARN kube-slack@3.6.0 No license field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /app
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/app'
npm ERR!  { [Error: EACCES: permission denied, access '/app']
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/app\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/app' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kube-dingtalk/.npm/_logs/2019-11-12T09_01_09_427Z-debug.log
The command '/bin/sh -c npm config set registry https://registry.npm.taobao.org && npm install --production' returned a non-zero code: 243
`

chown $user:$user /app

**Comment by gotoworld** [comment]
![image](https://user-images.githubusercontent.com/8605471/68660830-e2f0d280-0574-11ea-8868-de580f533f00.png)

**Comment by yangpeng14** [comment]
The error has been fixed
